name: Build and Push Docker image to ACR

on:
  push:
  workflow_dispatch:


env:
  IMAGE_NAME: my-java-app
  ACR_LOGIN_SERVER: ${{ secrets.ACR_LOGIN_SERVER }}  # e.g. myregistry.azurecr.io
  ACR_NAME: ${{ secrets.ACR_NAME }}                  # e.g. myregistry

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v5

      # Optional: build Java artifact before Docker build (keeps Docker builds faster)
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: "maven"

      
      - name: Build with Maven (explicit pom)
        run: mvn -f backend/pom.xml -B -DskipTests package

      # Login to Azure using OIDC (recommended) [1](https://learn.microsoft.com/en-us/azure/developer/github/connect-from-azure-openid-connect)[3](https://learn.microsoft.com/en-us/azure/developer/github/connect-from-azure)
      - name: Docker login (Azure)
        uses: docker/login-action@v3
        with:
          registry: gaptraiing.azurecr.io
          username: ${{ vars.AZURE_CLIENT_ID }}
          password: ${{ secrets.AZURE_CLIENT_SECRET }} 

      # Login Docker to ACR using Azure identity
      - name: Login to ACR
        run: az acr login --name "${ACR_NAME}"
        # ACR supports Entra ID based auth via `az acr login` [4](https://learn.microsoft.com/en-us/azure/container-registry/container-registry-authentication)[5](https://learn.microsoft.com/en-us/cli/azure/acr?view=azure-cli-latest)


      # Build and push Docker image with tags
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ vars.AZURE_ACR_NAME }}.azurecr.io/java-project:latest
            ${{ vars.AZURE_ACR_NAME }}.azurecr.io/java-project:sha-${{ steps.tag-vars.outputs.short_sha }}
